# 矩阵代数（Python版）

## NumPy基础

### NumPy ndarray：多维数组对象

一个ndarray是一个通用的多维同类数据容器，每个数组都有一个shape属性，用来表征数组每一维度的数量；每一个数组都要一个dtype属性，用来描述数组的数据类型。

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[-0.99533234,  0.91884098,  0.23828941],
       [-1.84226775, -0.84309985, -1.22662089]])

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

#### 生成ndarray

使用array函数，它可以接受任意的序列对象，生成一个新的包含传递数据的NumPy数组。

In [5]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### ndarray的数据类型

数据类型，即dtype，是一个特殊的对象，也称为元数据。

In [12]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [14]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

#### NumPy数组魔术

数组可以进行批量操作而无须任何for循环，称为向量化。

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [17]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float)
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 基础索引与切片

In [18]:
arr = np.arange(10)
arr[5]

5

In [19]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

数组的切片是原数组的视图，如果想要一份数组切片的拷贝而不是一份视图，就必须显式地复制这个数组，例如arr[5:8].copy。

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [21]:
arr2d[0][2]

3

In [22]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [23]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [24]:
arr2d[[True, False, False]]

array([[1, 2, 3]])

In [25]:
arr2d[[True, False, False], :2]

array([[1, 2]])

In [26]:
arr2d[arr2d > 5] = 0
arr2d

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

#### 神奇索引

In [27]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [28]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

#### 数组转置和换轴

数组拥有transpose方法，也有特殊的T属性。

In [29]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### 通用函数：快速的逐元素数组函数

通用函数是一种在ndarray数据中进行逐元素操作的函数。

In [31]:
arr= np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### 使用数组进行面向数组编程

In [32]:
arr = np.random.randn(4, 4)
arr

array([[ 0.38876813, -1.4947562 ,  1.14251399,  0.0913307 ],
       [-1.51946478,  1.19106484, -0.42201877, -1.2761836 ],
       [-1.00789297, -0.94802353,  0.69727745,  1.70428137],
       [-0.64026926, -0.0141641 ,  1.52501763, -0.97866848]])

In [33]:
arr > 0

array([[ True, False,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

In [34]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2,  2],
       [-2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2,  2, -2]])

In [35]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -1.4947562 ,  2.        ,  2.        ],
       [-1.51946478,  2.        , -0.42201877, -1.2761836 ],
       [-1.00789297, -0.94802353,  2.        ,  2.        ],
       [-0.64026926, -0.0141641 ,  2.        , -0.97866848]])

#### 数学和统计方法

In [36]:
arr = np.random.randn(5, 4)
arr.mean()

0.02466450568283458

In [37]:
arr.sum(axis = 0)

array([-1.78231379,  1.6406365 , -0.18237069,  0.81733808])

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [39]:
arr.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

#### 布尔值数组的方法

In [40]:
bools = np.array([False, False, True, False])
bools.any()

True

In [41]:
bools.all()

False

#### 排序

NumPy数组可以使用sort方法按位置排序。

In [42]:
arr = np.random.randn(6)
arr

array([ 0.20171933, -0.35591522, -2.1522556 ,  0.59255107,  0.60047034,
        1.22047472])

In [43]:
arr.sort()
arr

array([-2.1522556 , -0.35591522,  0.20171933,  0.59255107,  0.60047034,
        1.22047472])

#### 唯一值与其他集合逻辑

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

## 线性代数

### 矩阵乘法

NumPy的线性代数中*是矩阵的逐元素乘积，而不是矩阵的点乘积。矩阵乘法使用dot函数。

In [45]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])
x.dot(y)    # or np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

### 矩阵的逆

可用numpy.linalg的solve或者inv函数来求得矩阵的逆矩阵。

In [46]:
from numpy.linalg import solve, inv

A = np.array([[2, 5], [-3, -7]])
I = np.eye(2)

A_inv = solve(A, I)
print(A_inv)

print(inv(A))

[[-7. -5.]
 [ 3.  2.]]
[[-7. -5.]
 [ 3.  2.]]


### 行列式

可用numpy.linalg的det函数或者scipy.linalg.det来求得矩阵的行列式。

In [49]:
from scipy.linalg import det

A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))
print(det(A))

-2.0000000000000004
-2.0


### 特征根和特征向量

可用numpy.linalg的eig函数或者scipy.linalg.eig来求得矩阵的特征根和特征向量。

In [55]:
A = np.array([[2, 3], [3, -6]])
e, v = np.linalg.eig(A)
print(e)
print(v)

[ 3. -7.]
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]
